version: '3.8'

services:
  back:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - DB_HOST=${DATABASE_HOST}
      - DB_PORT=${DATABASE_PORT}
      - DB_NAME=${DATABASE_NAME}
      - DB_USERNAME=${DATABASE_USER}
      - DB_PASSWORD=${DATABASE_PASS}
    ports:
      - "3586:3586"
    volumes:
      - ./:/back/